PPS detector mapping records separation and serialization
CTPPS/cmssw pull request #79
Opened 2023-07-31 17:09 UTC by brzozia

#### PR description:

This PR addresses part of an issue from (https://github.com/cms-sw/cmssw/pull/40765).

In this PR:
* Introduction of new record: TotemAnalysisMaskRcd - separated from TotemReadoutRcd;
* Serialization of records and inner classes intended to be placed in the CondDB;
* Writer plugin and config for reading XML files and placing objects in SQLite;
* Updates of printer plugin which prints records content;

#### PR validation:

Validation has been made with use of new plugin which reads data from SQLite/XML file and drops them to text file.
All data from XML was dropped to SQLite in separate records and with different IOVs.
Then (using new plugin) objects were read from SQLite and dropped to text file.
Also data from XML files was read and dropped to other text file.
Then files were compared and their content was the same, as expected.

2023-07-31 20:52 UTC, grzanka commented on CondFormats/PPSObjects/src/classes.h
> +// namespace {
remove if not needed

2023-07-31 20:54 UTC, grzanka commented
In general looks good, ask @JanChyczynski for a review ! Squash commits may be needed.
Have you tried `runTheMatrix` tests here ?

2023-08-01 12:20 UTC, JanChyczynski commented
Please run
```
scram build code-checks
scram build code-format
```
And apply the changes

2023-08-01 15:35 UTC, JanChyczynski requested changes
Apart from some mostly minor things looks good

2023-08-01 15:35 UTC, JanChyczynski commented on CondTools/CTPPS/test/write-ctpps-totem_daqmap_cfg.py
> +  ))
```suggestion
      )
  )
```

2023-08-01 15:35 UTC, JanChyczynski commented on CalibPPS/ESProducers/plugins/PrintTotemDAQMapping.cc
> +      edm::LogInfo("PrintTotemDAQMapping channel mapping") << "    " << p.first << " plane " << p.second.plane << " channel " << p.second.channel;
After addressing the comment in `WriteCTPPSTotemDAQMappingMask.cc` about printing you could use the overloaded `<<` operators here.

Some more places like this in this file

2023-08-01 15:35 UTC, JanChyczynski commented on CalibPPS/ESProducers/test/scipt_test_many_writeTotemDAQMapping.py
> +            f.truncate()
Same issues as in [script-ctpps-write-many-XML-to-SQLite.py](https://github.com/CTPPS/cmssw/pull/79/files#diff-0e4fc4d568e2cae19bf49dd0c7cad074f6bc12fb0e8ed3cf69511660cd89711b):
* too long lines
* hard to understand: split to subfunctions or comment

2023-08-01 20:47 UTC, grzanka commented
@brzozia please squash the commits. I think we are ready to go with an official PR, assuming that runTheMatrix shows no problems

2023-08-03 11:33 UTC, JanChyczynski approved these changes
looks good

2023-11-02 21:00 UTC, merged